# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
!pip3 install -U tensorflow-gpu --quiet

     |████████████████████████████████| 380.8MB 58kB/s 
     |████████████████████████████████| 3.8MB 37.0MB/s 
     |████████████████████████████████| 450kB 53.8MB/s 
ERROR: tensorflow 1.15.0rc3 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.0 which is incompatible.
ERROR: tensorflow 1.15.0rc3 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.0.0 which is incompatible.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn import datasets
iris = datasets.load_iris()


In [56]:
type(iris)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = iris.data 
y = iris.target

In [58]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [59]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=42)

In [62]:
X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [63]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#model.add(tf.keras.layers.Reshape((784,),input_shape=(4,4,)))
#Add Dense Layer which provides 3 Outputs after applying softmax
model.add(tf.keras.layers.Dense(3, activation='softmax', input_shape=(4,)))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [68]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [69]:
model.fit(X_train, y_train, 
          validation_data=(X_test, y_test), 
          epochs=100,
          batch_size=32)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 6ms/sample - loss: 2.7632 - accuracy: 0.2857 - val_loss: 2.6195 - val_accuracy: 0.1579
Epoch 2/100
112/112 [==============================] - 0s 199us/sample - loss: 2.3102 - accuracy: 0.1607 - val_loss: 2.3138 - val_accuracy: 0.1316
Epoch 3/100
112/112 [==============================] - 0s 219us/sample - loss: 2.0531 - accuracy: 0.0893 - val_loss: 2.1683 - val_accuracy: 0.1579
Epoch 4/100
112/112 [==============================] - 0s 210us/sample - loss: 1.9417 - accuracy: 0.1339 - val_loss: 2.0779 - val_accuracy: 0.1842
Epoch 5/100
112/112 [==============================] - 0s 214us/sample - loss: 1.8797 - accuracy: 0.1875 - val_loss: 2.0155 - val_accuracy: 0.2105
Epoch 6/100
112/112 [==============================] - 0s 230us/sample - loss: 1.8211 - accuracy: 0.2589 - val_loss: 1.9559 - val_accuracy: 0.2368
Epoch 7/100
112/112 [==============================] - 0s 217us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [70]:
import numpy as np
input_data = np.expand_dims(X_test[0], axis=0)
print(input_data.shape)
pred = model.predict(input_data)
pred

(1, 4)


array([[0.08060874, 0.55502105, 0.36437026]], dtype=float32)

In [71]:
pred[0]

array([0.08060874, 0.55502105, 0.36437026], dtype=float32)

In [72]:
np.argmax(pred[0])

1

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
#Lets print the image as well
import matplotlib.pyplot as plt

#plt.imshow(X_test[0],cmap='gray')



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [75]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [152]:
# run this cell to upload file if you are using google colab
from google.colab import files
#files.upload()
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
df = pd.read_csv('/content/gdrive/My Drive/Collab/prices.csv')
#os.chdir('/content/gdrive/My Drive/Collab/')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [153]:
df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [154]:
df.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

In [155]:
df_date = df['date']
df = df.drop('date', axis=1)
df.columns

Index(['symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

In [156]:
df_symbol = df['symbol']
df = df.drop('symbol', axis=1)
df.columns

Index(['open', 'close', 'low', 'high', 'volume'], dtype='object')

In [157]:
df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [158]:
df.shape

(851264, 5)

In [159]:
df.dtypes

open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df = df.head(1000)

In [161]:
df.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [162]:
df.columns

Index(['open', 'close', 'low', 'high', 'volume'], dtype='object')

In [163]:
feature = df.iloc[:,0:4]
feature.columns

Index(['open', 'close', 'low', 'high'], dtype='object')

In [164]:
labels = df['volume']
labels

0       2163600.0
1       2386400.0
2       2489500.0
3       2006300.0
4       1408600.0
5       1098000.0
6        949600.0
7        785300.0
8       1093700.0
9       1523500.0
10      1653900.0
11       944300.0
12       744900.0
13       703800.0
14       563100.0
15       896100.0
16       680400.0
17       749900.0
18       574200.0
19       694800.0
20       896300.0
21       956300.0
22       997100.0
23      1200500.0
24      1725200.0
25      1946000.0
26      1319500.0
27       922400.0
28      1185100.0
29       921500.0
          ...    
970     9097500.0
971     2242100.0
972     6205100.0
973      864600.0
974      709200.0
975     1129600.0
976     3449300.0
977     7517100.0
978     2356500.0
979     4839200.0
980     3684600.0
981    14428400.0
982     1463300.0
983      749600.0
984    13355100.0
985    11538300.0
986     9931300.0
987    12906000.0
988      369900.0
989     2701000.0
990     2627800.0
991     3258700.0
992     5206100.0
993     7099000.0
994     77

In [165]:
labels = labels.divide(1000)
labels.head()

0    2163.6
1    2386.4
2    2489.5
3    2006.3
4    1408.6
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
feature = feature.to_numpy()
labels = labels.to_numpy()

In [0]:
feature = feature.astype('float32')
labels = labels.astype('float32')

In [168]:
feature

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)

In [169]:
labels

array([2.163600e+03, 2.386400e+03, 2.489500e+03, 2.006300e+03,
       1.408600e+03, 1.098000e+03, 9.496000e+02, 7.853000e+02,
       1.093700e+03, 1.523500e+03, 1.653900e+03, 9.443000e+02,
       7.449000e+02, 7.038000e+02, 5.631000e+02, 8.961000e+02,
       6.804000e+02, 7.499000e+02, 5.742000e+02, 6.948000e+02,
       8.963000e+02, 9.563000e+02, 9.971000e+02, 1.200500e+03,
       1.725200e+03, 1.946000e+03, 1.319500e+03, 9.224000e+02,
       1.185100e+03, 9.215000e+02, 4.409000e+02, 1.244300e+03,
       6.813000e+02, 4.112000e+02, 4.473000e+02, 5.592000e+02,
       4.599000e+02, 9.716000e+02, 6.941000e+02, 1.159600e+03,
       8.847000e+02, 6.920000e+02, 8.980000e+02, 8.445000e+02,
       7.965000e+02, 4.168000e+02, 5.902000e+02, 4.951000e+02,
       5.158000e+02, 5.621000e+02, 8.093000e+02, 1.607300e+03,
       1.001300e+03, 7.114000e+02, 4.442000e+02, 5.341000e+02,
       7.982000e+02, 5.910000e+02, 4.432000e+02, 5.780000e+02,
       7.651000e+02, 5.143000e+02, 1.150000e+03, 2.0353

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [170]:
feature = tf.math.l2_normalize(feature)
feature

<tf.Tensor: id=3774, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

In [172]:
weight


<tf.Tensor: id=3726, shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [173]:
bias

<tf.Tensor: id=3766, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [178]:
for i in range(100):
    
    w, b = train(feature, labels, w, b)
    print('Current Loss on iteration', i, loss(labels, prediction(feature, w, b)).numpy())

Current Loss on iteration 0 235093000.0
Current Loss on iteration 1 234061090.0
Current Loss on iteration 2 233069760.0
Current Loss on iteration 3 232117820.0
Current Loss on iteration 4 231203820.0
Current Loss on iteration 5 230325870.0
Current Loss on iteration 6 229482770.0
Current Loss on iteration 7 228672880.0
Current Loss on iteration 8 227895330.0
Current Loss on iteration 9 227148210.0
Current Loss on iteration 10 226431040.0
Current Loss on iteration 11 225742290.0
Current Loss on iteration 12 225080690.0
Current Loss on iteration 13 224445260.0
Current Loss on iteration 14 223835140.0
Current Loss on iteration 15 223249310.0
Current Loss on iteration 16 222686460.0
Current Loss on iteration 17 222145890.0
Current Loss on iteration 18 221626900.0
Current Loss on iteration 19 221128460.0
Current Loss on iteration 20 220649740.0
Current Loss on iteration 21 220189950.0
Current Loss on iteration 22 219748180.0
Current Loss on iteration 23 219324350.0
Current Loss on iteration 

### Observe values of Weight
- Print the updated values

In [179]:
#Check Weights and Bias
print('Weights:\n', w.numpy())


Weights:
 [[54.94985 ]
 [55.04922 ]
 [54.392685]
 [55.49984 ]]


### Observe values of Bias
- Print the updated values

In [180]:
print('Bias:\n',b.numpy())

Bias:
 [4621.736]
